### ISSUE TITLE
Visualization bug

### ISSUE THREAD

**Issue by kavinat** [UnaNancyOwen/VelodyneCapture#11]
Hello, 

During the visualization I noticed that at times the widget is displaying multiple frames at once. Is there a solution  for it?

 ```cpp
if( last_azimuth > azimuth ) //Last azimuth =0 & azimuth= Firing data rotational position
{
    mutex.lock();
    FBufferLasers= FLasers; //FLasers: Data of Next Round FBufferLasers: Data being displayed
    mutex.unlock();
    FLasers.clear();
}
```

Instead of showing one complete round at a time is shows multiple rounds of data at once. Why is that happening and what can I do to curb it?

**Comment by UnaNancyOwen** [comment]
I don't know details of your problem.
You need to tell more details (environment, source code, reproduce steps, screen shot, etc.).

BTW:
Probabry, The part of code that you showed is not written by me.
If it is your own source code, The cause of your problem may be in your source code.
I can't advise anything about it.

**Comment by kavinat** [comment]
I am using the same code. Just changed the names. In VelodyneCapture.h this is the code you used to capture one round of rotation data:

```cpp
// Complete Retrieve Capture One Rotation Data
if( last_azimuth > azimuth ){
    // Push One Rotation Data to Queue
    mutex.lock();
    queue.push( lasers );
    mutex.unlock();
    lasers.clear();
}
```

But when I use it, at times 3-4 rounds of data is bring shown as one. 

I am working on VS2015, win7. 

![double frames](https://user-images.githubusercontent.com/20070558/31937339-598afd04-b8b4-11e7-9745-352ac67a0fed.PNG)

As you see from the image two frames are showing up at the same time.

**Comment by UnaNancyOwen** [comment]
I think there is a problem in source code for visualize data.
Does that problem also occur in sample program of viewer ([VelodyneCapture/sample/viewer](https://github.com/UnaNancyOwen/VelodyneCapture/tree/master/sample/viewer))?

Note:
Please read document about code blocks of GitHub flavored markdown.
It makes the source code easier to read.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by kavinat** [comment]
Yes I am using the viewer program. I believe it is the capturing of data in the VelodyneCapture headerfile that might be the issue like I mentioned in my comment above. Is there a way to avoid such multiple frames?

**Comment by UnaNancyOwen** [comment]
Hmmm, It seems to be a bug of VelodyneCapture class.
Please try add <code>static</code> modifier to VelodyneCapture.h [#L361](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/viewer/VelodyneCapture.h#L361) and [#L469](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/viewer/VelodyneCapture.h#L469).
And, Please report the results. Thanks,

```patch
- double last_azimuth = 0.0;
+ static double last_azimuth = 0.0;
```

**Comment by UnaNancyOwen** [comment]
Fix this bug in this commit https://github.com/UnaNancyOwen/VelodyneCapture/commit/b77922fdd7fd4bf1ab4cdbdc911817e1b9c7da7f.

**Comment by kavinat** [comment]
Thank you for the suggestion. It has worked perfectly well and I am getting one frame at a time on the widget now.
