### ISSUE TITLE
visualizing two pcap files at once.

### ISSUE THREAD

**Issue by kavinat** [UnaNancyOwen/VelodyneCapture#12]
This is not necessarily a bug but rather a question. I was able to successfully read and visualize the pcap file using this code. However, I want to apply ransac to it and show the floor and objects in different colors. 

So far I manage to show only one point cloud using WCloud in any color I want, either floor or objects, but not both in the same window. How can I achieve this? Would it be possible using WCloudCollection? Please let me know.

**Comment by UnaNancyOwen** [comment]
I think it would be good to pass in color array that colors the objects area to any colors to second argument of [cv::viz::WCloud](https://docs.opencv.org/trunk/db/d82/classcv_1_1viz_1_1WCloud.html#a141f2d37cf2babf9b3a4200f942d0eb1).
If each is a separate data, it should use [cv::viz::WCloudCollection](https://docs.opencv.org/trunk/de/d47/classcv_1_1viz_1_1WCloudCollection.html).
If you want more information, Please post to [OpenCV user Q&A forum](http://answers.opencv.org/questions/).

BTW: Do you plan to implement object detection yourself? I think you should be good to use PCL for your use case. It has some functions to detect objects.

**Comment by kavinat** [comment]
Yes, I am trying to implement object detection myself, but for now I am working on just visualizing. I am using PCL for implementing RANSAC and future filters and algorithms, but for visualization I am using open CV since I am using pre-built PCL.
