### ISSUE TITLE
Data race with atomic variable run

### ISSUE THREAD

**Issue by lasdasdas** [UnaNancyOwen/VelodyneCapture#14]
Hey, 

We currently used your drivers to read PCAPs and we had many problems. Fortunately we found the potential problem. 

### The issue
When using the pcap, we sometimes could read the content of the file, and sometimes the program (simple project main.cpp) went though without entering
``` 
while( capture.isRun() ){ 
```
Sometimes exiting with a segfault also. This we haven't figured it out yet. 

### Proposed solution.
We think there might be a data race going on in here. 

Run is initialized here, after the creation of the capturePcap thread. 
https://github.com/UnaNancyOwen/VelodyneCapture/blob/5295e3a9d6662038405fa377b44c368ea84e2835/sample/simple/VelodyneCapture.h#L314-L316

We think it might be the case that the loop on main, goes though there, before the thread has been created, and therefore isRun is false. 
https://github.com/UnaNancyOwen/VelodyneCapture/blob/5295e3a9d6662038405fa377b44c368ea84e2835/sample/simple/main.cpp#L29

We propose setting the variable to true before creating the thread here:
https://github.com/UnaNancyOwen/VelodyneCapture/blob/5295e3a9d6662038405fa377b44c368ea84e2835/sample/simple/main.cpp#L29

or covering the whole process with a lock. We have tested putting the run=true line before launching the thread and it seems to work

**Comment by UnaNancyOwen** [comment]
Thanks, It is right. Fix in 02ccca7.

**Comment by lasdasdas** [comment]
That was fast! Thanks
