### ISSUE TITLE
VLP-16::lut wrong

### ISSUE THREAD

**Issue by dongyu728** [UnaNancyOwen/VelodyneCapture#15]
const std::vector<double> lut = { -15.0, 1.0, -13.0, **-3**, -11.0, 5.0, -9.0, 7.0, -7.0, 9.0, -5.0, 11.0, -3.0, 13.0, -1.0, 15.0 };
This is Wrong.I use this code but get a wrong result because the user-guide pdf of vlp-16 also has this problem.
I compared this code and veloview to convert a pcap to csv,and find this problem.
It should be this which get  correct results.
 const std::vector<double> lut = { -15.0, 1.0, -13.0, **3**, -11.0, 5.0, -9.0, 7.0, -7.0, 9.0, -5.0, 11.0, -3.0, 13.0, -1.0, 15.0 }
So I wish you can see this and update your code.

**Comment by lasdasdas** [comment]
Pull the code again, this was fixed in here 5295e3a9d6662038405fa377b44c368ea84e2835

**Comment by lasdasdas** [comment]
This is fixed. It can be closed.
