### ISSUE TITLE
What are the packages required ?

### ISSUE THREAD

**Issue by Raj7kumar7** [UnaNancyOwen/VelodyneCapture#26]
Hello
Can you tell me what are the packages i have to install to run it?
Also,Can it run on Ubuntu??

Thanks

**Comment by UnaNancyOwen** [comment]
Please read [README](https://github.com/UnaNancyOwen/VelodyneCapture#environment). This class required Boost and PCAP.
@lasdasdas is running this class in Ubuntu. Therefor, It is Yes.
