### ISSUE TITLE
error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’

### ISSUE THREAD

**Issue by Durant35** [UnaNancyOwen/VelodyneCapture#3]
+ make error
```sh
......../VelodyneCapture.h:74:37: error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
             std::atomic<bool> run = false;
```

**Comment by UnaNancyOwen** [comment]
Please rewrite [VelodyneCapture.h#L74](https://github.com/UnaNancyOwen/VelodyneCapture/blob/master/sample/VelodyneCapture.h#L74) as follows, and try it.

```cpp
// std::atomic<bool> run = false;
std::atomic_bool run = { false };
```

**Comment by Durant35** [comment]
Great! it works. Thanks very much for your timely reply. Awesome.

**Comment by wuyang-dl** [comment]
thanks  it works！

**Comment by phampham97** [comment]
thanks it works！
static inline std::atomic<uint64_t> m_NextId = 100;
replace
static inline std::atomic<uint64_t> m_NextId = {100};
