### ISSUE TITLE
Error in parseDataPacket

### ISSUE THREAD

**Issue by AJMena** [UnaNancyOwen/VelodyneCapture#38]
Hello there.
There's an error in parseDataPacket in this line:
`double laser_relative_time = LASER_PER_FIRING * time_between_firings + time_half_idle* (laser_index / max_num_lasers);`
It should be like this:
`double laser_relative_time = laser_index * time_between_firings + time_half_idle* (laser_index / max_num_lasers);`
Hope it helps.

**Comment by UnaNancyOwen** [comment]
@lasdasdas What do you think?

**Comment by lasdasdas** [comment]
I have not been around for quite a while, sorry for that. It seems that this is an issue. I'll check it out later.

**Comment by lasdasdas** [comment]
Fixed in 80970c8. Good find @AJMena .
