### ISSUE TITLE
debug error in simple 

### ISSUE THREAD

**Issue by kavinat** [UnaNancyOwen/VelodyneCapture#7]
Hi. I tried to execute the "simple" program in the same you provided and used cmake. 

opencv 3.3.0
visual studio 2015 community
win32 platform
WinPcap
Boost 1.64.00 

when I try to execute in debug mode I am getting an error window saying 

abort() has been called. Please try debugging again! 
Assert failed: packet->sensor type= 0x22 in VelodyneCapture.h line 435

Can you please tell me how can I fix it? 

EDIT: If I remove the assertion command from the headerfile, it is giving me an output. Is the assertion critical to the output?

**Comment by UnaNancyOwen** [comment]
@kavinat It is a bug of sensor type check.
I added HDL-32E (0x21) to the sensor type check. (https://github.com/UnaNancyOwen/VelodyneCapture/commit/976679473253ec6aaea313404d9aa29b397f4591)
Please try again. Thanks,
